### ISSUE TITLE
Move Wiki to website, possibly using hugo learn theme

### ISSUE THREAD

**Issue by BeatLink** [gobolinux/Documentation#11]
Moving the wiki to an actual website would add several benefits, especially if using the hugo-learn-theme. You can view a demo of the theme here:

https://themes.gohugo.io/theme/hugo-theme-learn/en/

With the hugo learn theme, you can still store content in markdown but you have many features including searching, sections and subsections, images, code blocks, frontmatter and so much more.

**Comment by Nuc1eoN** [comment]
This all makes sense but who is going to implement this?

Are you interested in Contributing?

**Comment by BeatLink** [comment]
Id be happy to!

**Comment by Nuc1eoN** [comment]
add me on discord nuc#5557

**Comment by dubiouscript** [comment]
aparently

> Currently, GitHub prevents crawling of repository Wiki pages. As such, GitHub Wikis are invisible to search engines

> If you are a GitHub Wiki maintainer, you may want to consider GitHub Pages backed by a public repository for your community's content as a more stable, blessed, and probably higher search ranking alternative.

source : https://github-wiki-see.page/

**Comment by Nuc1eoN** [comment]
Hi, this proposal has been implemented, see https://github.com/gobolinux/Documentation and https://wiki.gobolinux.org/.
Closing.
