### ISSUE TITLE
Update instructions for setting up gobolinux with VirtualBox

### ISSUE THREAD

**Issue by BeatLink** [gobolinux/Documentation#13]

**Comment by Nuc1eoN** [comment]
What is the issue with the current instructions?

**Comment by BeatLink** [comment]
I dont recall, I havent been using gobolinux for some years now. IIRC it had something to do with grub and partitioning schemes but if the current build works fine, this can be closed.

**Comment by Nuc1eoN** [comment]
I have not noticed any particular issues. So I am closing for now.
Thanks for reporting back!
