### ISSUE TITLE
old wiki content / deadlinks =/

### ISSUE THREAD

**Issue by dubiouscript** [gobolinux/Documentation#19]
trying to follow this link 
http://wiki.gobolinux.org/index.php?title=The_GoboLinux_Filesystem_Hierarchy

im redirected to this link 

https://github.com/gobolinux/Documentation/wikiindex.php?title=The_GoboLinux_Filesystem_Hierarchy

which do not exist !

where is the old tiddly wiki content ?? ! ( eg wiki markup plaintext / ect )
could it be made avalable .. even unrendered wiki markup can be read/usefull !

perhaps a page about the old content could be created in this wiki 
and the old wiki links redirect that page  ??

... i was going ask which wiki backend was used but just managed to find [this archive](http://web.archive.org/web/20160408145555/http://wiki.gobolinux.org/index.php?title=The_GoboLinux_Filesystem_Hierarchy) 
it appears to be MediaWiki

..it might even be posible to get *something* to render the text in browser 

with that in mind 
"Move Wiki to website" https://github.com/gobolinux/Documentation/issues/11

could 
gh pages / ci scripts / or similar  
to import/host this https://github.com/gobolinux/Documentation/wiki.git md content 
with somthing like zeromd : https://github.com/zerodevx/zero-md
:question: 

... anyway i found https://github.com/gobolinux/Documentation/wiki/The-GoboLinux-Filesystem-Hierarchy
where the redirect
https://github.com/gobolinux/Documentation/wikiindex.php?title=The_GoboLinux_Filesystem_Hierarchy
 should have pointed =/

it looks like in this case replacing 
'wikiindex.php?title=' with 'wiki/
and 
underscore with dash 

would reslove the correct url

**Comment by dubiouscript** [comment]
aparently  
>Currently, GitHub prevents crawling of repository Wiki pages. As such, GitHub Wikis are invisible to search engines

>If you are a GitHub Wiki maintainer, you may want to consider GitHub Pages backed by a public repository for your community's content as a more stable, blessed, and probably higher search ranking alternative. 

spurce : https://github-wiki-see.page/

**Comment by Nuc1eoN** [comment]
Hi, I see the issue, however I do not think it is feasable for the time and effort to implement such a redirection system. A lot has changed and we have moved to a new wiki framework now, see https://github.com/gobolinux/Documentation/ and https://wiki.gobolinux.org/.

The new wiki has a handy search function, so it should not be too difficult to find the content.

**Comment by dubiouscript** [comment]
> Hi, I see the issue, however I do not think it is feasable for the time and effort to implement such a redirection system.
ftr most server have a module for this 

>A lot has changed and we have moved to a new wiki framework now, see https://github.com/gobolinux/Documentation/ and https://wiki.gobolinux.org/.
> 
> The new wiki has a handy search function, so it should not be too difficult to find the content.
ohh shiny !!
