### ISSUE TITLE
http://www.gobolinux.org/?page=devteam could need a small update

### ISSUE THREAD

**Issue by shevegen** [gobolinux/Documentation#2]
Hi Lucas and Hisham and others,

The page at:

http://www.gobolinux.org/?page=devteam

I believe it may not be completely up to date anymore after the git transition.

For example, it reads:

"Developers with CVS commit access are listed below as "dev"."

I believe it may have to be changed to git and perhaps updated.

Sorry to bother with such small things. :)

**Comment by hishamhm** [comment]
Thanks! It's updated now in the new website.
