### ISSUE TITLE
Please add an OpenSSL guide here (specific for gobolinux that is)

### ISSUE THREAD

**Issue by rubyFeedback** [gobolinux/Documentation#21]
Right now I have an issue with certificates. I compiled the latest openssl from source, all
fine, but now I am not sure how to update the ssl certificates. Because of this I can
not really download anything using secure connections; I transfer via a secondary
computer, then compile from source as-is.

Having the procedure in a text file how the gobolinux dev team operates here may
help (I mean the manual steps; I can't understand the shell scripts really).

**Comment by Nuc1eoN** [comment]
I think we have that already: https://wiki.gobolinux.org/Overview/Installing-Gobolinux/GoboLinux-017-Known-Issues-and-
Fixes/#update-expired-ssl-certificates

Is anything missing?

**Comment by Nuc1eoN** [comment]
Closing, as I believe we have it now properly documented :)
