### ISSUE TITLE
Network task

### ISSUE THREAD

**Issue by mbb78** [gobolinux/Documentation#4]
Hi!

Sorry if I'm not posting at the right place.

I've just recently got to know Gobo through a [Manjaro Forum discussion topic](https://forum.manjaro.org/t/what-is-gobo-gobolinux-what/10879/1), and I quite like its concept. I installed it on a VM and all went well, except for:

a) Gobo Wiki, on the [Network Configuration section](https://github.com/gobolinux/Documentation/wiki/Configuring-the-boot-process#Network_configuration), refers the interface can be switched to "up" by issuing `StartTask Network [interface]`. However, the output says there's no "Network" task. So I looked at the tasks and found `DHCPNetwork[...]` (I'm not sure of the file name because I'm not at that machine now). I looked into the file and saw it should be called by the Network task, which wasn't present. I got the network working by calling directly with `StartTask DHCPNetwork[...] [interface] [timeout]` I had to define the timeout otherwise it wouldn't connect. I wonder if you missed something on the LiveCD (a missing task) or if I missed something myself!

b) When I shutdown the machine it stops all the processes but doesn't power off. I shut it down by exiting the WM and issuing `shutdown now` I tried using the shutdown option (`-P` I think) but it made no difference. Am I missing something or is the VM badly configured?

I have some experience with Linux, but I'm not an expert nor an IT guy (I'm still learning). I also haven't read the whole Wiki yet (I might have missed something). So, I'm sorry if I'm wasting your time - I just thought there could be some mistake on the Wiki or some missing Task and wanted to contribute.

I don't have much free time at the moment, but I intend to slowly customise/use Gobo and hopefully I can contribute in the future. I really like the idea of having applications which are agnostic of where they should be and where shared components should be located. Thank for your work and for taking the time to read this.

Cheers,

**Comment by Nuc1eoN** [comment]
Hey @mbb78 that is a valid question!
If you still have issues with this please post a thread about this in our [forums](https://gobolinux.discourse.group/) :)
