### ISSUE TITLE
What is the complete definition and origin of Gobo in the name GoboLinux?

### ISSUE THREAD

**Issue by BoQsc** [gobolinux/Documentation#9]

**Comment by waldyrious** [comment]
For what it's worth, here's what the [FAQ](https://github.com/gobolinux/gobolinux.org/blob/98ecae358fe6d5fc0e84a0ba486667190cdc921c/lang/en_US/pages/faq.html#L219-L239) says:

> **Who is Gobo?**
>
> Apart from Fibo, his loyal servant, no one who saw him survived to tell the story. Beyond that, we never risked digging any deeper into the subject.
> [...]
> You may disregard the [...] above -- they are just one of the many internal jokes in the GoboLinux world.

**Comment by Nuc1eoN** [comment]
Hello, I feel it is better to reserve this Issues page for specific issues with our documentation.

A better place would be to ask in our forums at https://gobolinux.discourse.group/ (which will also benefit future generations) :)
